### ISSUE TITLE
Closed Roles

### ISSUE THREAD

**Issue by christyjestin** [pittcsc/Summer2023-Internships#1104]
I might be missing something or reading too much into it, but it looks like several of the positions that are listed as closed aren't actually closed. For example, the SWE position at Applied Intuition in Mountain View is [open](https://boards.greenhouse.io/appliedintuition/jobs/4045296005?gh_jid=4045296005). Some of the positions were actually closed, so it could totally be positions opening back up or something else -- I don't know; just wanted to point it out cause I've seen a few examples at this point.

On a separate note, I think it would be worth adding a comment at the top saying that even if the listed intern role is closed at a company, that doesn't mean they're completely done with hiring and all roles (including ones that aren't listed on this repo) are closed.

**Comment by Verse1** [comment]
Agreed, I think they should be marked as closed, but the link to it should still exist in case they ever bring it back up again, and then someone can make a pr indicating that it is open once again.

**Comment by Zmwang622** [comment]
Thanks for sending the Applied Intuition posting, updated the repo accordingly!

Since the repo list is so comprehensive, it's hard for us to actively track which postings are re-opened and which ones are permanently closed. If anyone ever finds a new application link for a posting that was previously closed (like Applied Intuition), we'd really appreciate a new PR and what not! 

The maintainers of this repo are students/new grads too and we're all trying our best 🙏

**Comment by Zmwang622** [comment]
In response to Verse1, I think when companies reopen a position the url will be different? Hard to say for sure, but the UX of someone opening expired/closed links only to realize the posting was closed feels unideal

**Comment by christyjestin** [comment]
Sorry for late response.

I see what you're saying. Do you mind adding a note at the top saying that roles can reopen and what I said here: "even if the listed intern role is closed at a company, that doesn't mean they're completely done with hiring and all roles (including ones that aren't listed on this repo) are closed."
