### ISSUE TITLE
A Question ...?

### ISSUE THREAD

**Issue by AbubakrChan** [pittcsc/Summer2023-Internships#1703]
If the location column of a job says "<country>,Remote>" do this means that only people from that country can apply for remote job or anyone worldwide can apply? 
Thank you

**Comment by charitarthchugh** [comment]
That depends on the individual job posting.  Some companies are US remote
only,  for example.

**Comment by AbubakrChan** [comment]
Thank you for replying
How can I know if some company is accepting application worldwide?

**Comment by ewang2002** [comment]
Honestly, it's kind of hard to tell and will require a fair amount of trial and error. A few things that can probably help:
1. If the company puts "Remote, US" or some variant of it (e.g., a remote position but a US state is specified), it probably means that they only accept applications from candidates in the US.
2. Otherwise, you can look at sponsorship requirements -- if a company explicitly states that they will not sponsor visas or require US citizenship, it probably means they will only accept applications from candidates in the US/Canada. 
3. If you want to do some research on the company (which isn't necessarily a bad idea), you can probably find some information about their employees; some companies usually like to talk about how their employees can work from around the world.

But, yeah, it's going to be hard to filter remote positions like that.
