### ISSUE TITLE
Clean up repo branches

### ISSUE THREAD

**Issue by tianyizheng02** [pittcsc/Summer2023-Internships#1905]
There's an `owini-gitlab` branch that hasn't be active for a few months now. @owini, is that branch still being used? Is it safe to delete that branch?

Also, I'm not sure why our main branch is called `dev`. I'm guessing the actual main branch was deleted at some point and `dev` became the new main branch? If that's the case, then we could rename it to `main` for clarity, but anyone with push access to `dev` would have to update their remotes. @owini @ewang2002, thoughts?

**Comment by ewang2002** [comment]
> There's an owini-gitlab branch that hasn't be active for a few months now. @owini, is that branch still being used? Is it safe to delete that branch?

Yeah, I think it's safe to delete the branch. The branch was merged through #1769. 

> Also, I'm not sure why our main branch is called dev. I'm guessing the actual main branch was deleted at some point and dev became the new main branch? 

I have no idea why the branch is named `dev`. The branch being named `dev` was a thing even after I became a maintainer. I'm indifferent towards changing the branch name -- on one hand, you're right that it'll be a little more clear but, on the other hand, no one has really noticed (or cared to mention the branch name) for the past year or so.

I'll let @owini (cc @Zmwang622) make the decision here, since she's been maintaining this repository far longer than I have.

**Comment by Duykhoi311204** [comment]
``

**Comment by owini** [comment]
^not an active branch--thanks both!
