### ISSUE TITLE
Questions regarding hiring timeline for some startups in the list

### ISSUE THREAD

**Issue by Qiaolin-Yu** [pittcsc/Summer2023-Internships#1911]
Could I know how was it determined that some companies in the list (e.g., MosaicML, Certik, and Ramp) are recruiting for internships for the Summer of 2024 instead of the Summer of 2023? It seems more probable that startups would be hiring for the nearer term, i.e., Summer 2023.

**Comment by ewang2002** [comment]
Hey! We've generally been pretty lax with internship postings -- if the job posting doesn't explicitly say that the internship is for a specific term (or otherwise doesn't have any information that may imply that the internship is for a specific term, e.g., "June to December 2023"), then we can assume that it's a summer 2024 internship until someone else confirms otherwise (e.g., #1910). 

It has always been the case that a particular internship listed here isn't actually for the next summer but for another term. But, these cases are usually in the minority so it's not really worth the effort for the maintainers to validate that an internship is for summer 2024 (doing so would basically require us to either contact the recruiters, or find past internship offerings and guess whether the current posting is for the upcoming summer or another term).

Does this answer your question?

**Comment by Qiaolin-Yu** [comment]
Thank you for your answer. This is very helpful.
