### ISSUE TITLE
Where to find internship information?

### ISSUE THREAD

**Issue by terryyLi** [pittcsc/Summer2023-Internships#1978]
Hi I’d like to contribute here. Can anyone share how did you find which position is open? Is it through another platform like LinkedIn?

**Comment by owini** [comment]
Great! Normally job listings are posted on company or independent job boards, LinkedIn, and other platforms like Angellist.

**Comment by tianyizheng02** [comment]
@terryyLi I should also add, however, that if you find an open position, then you should contribute the position's _official_ page, not a page from a third-party site like LinkedIn. This is so that we can get the most accurate information for internship postings.

For example, let's say you find an open internship position at Company X on LinkedIn. Instead of adding the link to the LinkedIn post to the repo, you should add the link to the position's posting on Company X's own careers site.
