### ISSUE TITLE
Some of the internships added recently don't seem to be Summer 2024

### ISSUE THREAD

**Issue by gpersonnat** [pittcsc/Summer2023-Internships#2006]
The internships listed from Rakuten to Docugami do not seem to be Summer 2024 internships based on the application descriptions.

**Comment by ncbarta** [comment]
Hello, I was the person to add those internships. Based on how recently they were posted, I have taken the assumption that they are for summer 2024. Also, off-season internships are normally specified with "Fall 20XX", "Spring 20XX", or other term. With nothing to indicate an internship being off-season, I wouldn't really know where else to place it.

There is obviously a risk when adding these companies.

One of the bigger risks would be adding a fake recycled posting, but the sources of these postings look to be legitimate, and as a policy, I check if I can reach a job posting through the company's official website > careers page.

I'll ask some maintainers to review.

**Comment by gpersonnat** [comment]
Hi @NathanBarta, thank you for the response, and I understand. 

I think an issue with placing those internships under Summer 2024 is that it adds a lot of clutter to this repo. When I saw that various internships were added, I was thinking that there were a lot more 2024 internships open right now, but I was disappointed to see that these (presumably) weren't actually summer internships. 

I suggest the best option is to just have a README for "Other" internships (that don't fall into a seasonal category).

**Comment by tianyizheng02** [comment]
Hi @gpersonnat, thanks for bringing this to our attention. I completely agree that this is a valid concern, but unfortunately I don't think there's much that we can actually do about these kinds of postings.

The issue is that many, many companies simply don't state what term an internship is for—even when there is one. The vast majority of internships are for the summer term, so it's often just taken as a given that an internship posting is for the summer, at least in my experience. Because of this, there's really no good way to verify these kinds of postings without reaching out to the company itself on a case-by-case basis. The precedent for these kinds of postings has been to give them the benefit of the doubt and only relocate them when we get explicit evidence to the contrary. It's definitely not ideal, but I think that's what we should go with here. Setting a precedent of marking unspecified internships as "other" and taking them off the list would result in way too many false negatives.

I've talked to @NathanBarta already, and he reported that he originally found most of the postings from recent job postings on LinkedIn. I think it's reasonable to assume that these postings are indeed for the summer simply by virtue of it being much more likely (it's pretty late for fall internship postings at this point in the year). Going forward, I think establishing some way of enforcing transparency about where one originally found a posting (company careers page, LinkedIn, etc) would help us verify postings like this.

I hope this addresses your concerns. As for the postings currently in the repo, I'd say that it's safe to assume that they're for the correct term.
