### ISSUE TITLE
Add a New List Featuring only Internships from Fortune 500 Companies

### ISSUE THREAD

**Issue by friesentyler** [pittcsc/Summer2023-Internships#2056]
Many internships at prestigious big tech firms or quant trading companies (which this list primarily is composed of) pose challenges for students from non-top 20 universities due to their competitive nature and higher bar for resume screening. Adding a new list for just Fortune 500 companies would help students who have less impressive resumes and provide a pathway for students to build their credentials by putting a more recognizable name on their resume for future internships.

**Comment by ncbarta** [comment]
That's a really bad mentality. 

Yes, getting internships is hard. You shouldn't just discount yourself or others because they don't have a fancy name on their resume. Your post doesn't explain why a second list would help. The internships on the repo right now are skewed towards really competitive positions because it is early in the application season. 

Categorizing opportunities by prestige/size is biased and unproductive. It'd place undue burden on our contributors.

You kinda got to the point yourself: you have to start somewhere. People are going to start in different places. Also, you'd be surprised by how similar the students who really apply themselves from T-20 and non-T-20 schools are. Maybe the best role for somebody would be at an *unknown* company. It's all about learning.

----

- Apply everywhere you meet some of the requirements.
- Get your resume in front of people. Seek reviews.
