### ISSUE TITLE
New Feature Request: sponsorship information

### ISSUE THREAD

**Issue by raychiu99** [pittcsc/Summer2023-Internships#2155]
### Improvement

I think the old version stated that if the internship requires citizenship or if it sponsors. Are we able to add that feature back?

**Comment by marmikpatel19** [comment]
I agree with this! Sponsorship information is quite important to many users!

**Comment by Yanyu0203** [comment]
Totally Agree!!!! Sponsorship information is really important

**Comment by chingizof** [comment]
Agree, Sponsorship information is extremely helpful

**Comment by hemanthy1** [comment]
#2144 Has a discussion about it and they said they are working on it and will be out soon

**Comment by matttreed** [comment]
Hey everyone! Thanks for the feedback. We're currently working on a better way of displaying this information that should be done in the next couple days, but for now we're just sticking with what the old version had: stating in parentheses if a posting requires citizenship or doesn't offer sponsorship

**Comment by matttreed** [comment]
The time has come, sponsorship information is now standardized across the repo! Check out the new legend on the README to see what the emojis mean. I was only able to show information about sponsorships that was already stated on the repo, but any new internships will be accurate since the form now asks about sponsorship status. If any internship doesn't offer sponsorships but doesn't have the emoji, then feel free to submit an edit internship issue and it'll be fixed
