### ISSUE TITLE
<issue>

### ISSUE THREAD

**Issue by miguelangeltamargo** [pittcsc/Summer2023-Internships#2563]
### Issue/Question

On Firefox 117 I had the Simplify Copilot extension installed, and it would randomly cause all my tabs to reload/load after 20 min of starting Firefox and this reload/load seemed to stall as the CPU usage of Firefox would read metrics of 160% and the system metrics would reach 100%.
I am on macOS.

**Comment by cosmicRover** [comment]
Ahhhh so that is what causing my tabs to reload!!!!

**Comment by cwcoogan** [comment]
Thanks for bringing this up. I will work with the team to determined the route of action to ensure this is addressed. Thank you!

**Comment by matttreed** [comment]
Thanks for bringing this up @miguelangeltamargo ! The engineers are working on it as we speak <3

**Comment by rushilsrivastava** [comment]
Thanks for reporting @miguelangeltamargo and @cosmicRover! This has been fixed in the patch released [yesterday](https://addons.mozilla.org/en-US/firefox/addon/simplify-jobs/versions/5619766). The bug was unfortunately caused by a mismatch in the Firefox vs Chrome spec in [checking for updates](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/requestUpdateCheck). 

Thanks to everyone who submitted a bug report, this helped us fix this quickly. You can help report bugs to our team via the steps [here](https://simplify.jobs/support), or by [emailing us](mailto:support@simplify.jobs).
