### ISSUE TITLE
Missing text in company column

### ISSUE THREAD

**Issue by andylin2004** [pittcsc/Summer2023-Internships#2745]
### Issue/Question

For some internships, like Robinhood ones, the company name does not show up at all for some reason. Either a processing bug or a someone deleted some company names bug

**Comment by cwcoogan** [comment]
Thank you, I noticed that too. I will make the team aware and make sure we correct this,

**Comment by rushilsrivastava** [comment]
I made the change to easily separate between companies that post on the same day. Perhaps adding an emoji or something will be better than just a blank space though. Happy to take suggestions or revert the change though!

**Comment by etw0001** [comment]
hey rushil, we're currently parsing pittcsc and displaying the data in our website, and since we are doing a null checker for the fields to determine whether or not they are being displayed, all the items without a name aren't appearing anymore. We were hoping you could revert the changes so that this issue is fixed.

**Comment by rushilsrivastava** [comment]
Based on external feedback, we're leaning toward keeping this the current format with the addition of a pipe (`|`) instead of a blank space. 

@etw0001 Can you update your scraper to handle this?

**Comment by rushilsrivastava** [comment]
Closed by 1c0e591
